### PR TITLE
Refactored project

### PR DESCRIPTION
**Pull request by comtihon**
Refactored project.
Split test code and working code.
Got rid of common tests if favor of eunit.
Dismantled one huge module `wamper_protocol` 1K+ codelines to two more modules.
No changes in logic.

### CODE REVIEW

**Comment by bwegh** [comment]
looks great, thanks for your help!

could you please adjust the copyright headers and licences, thanks

**Comment by comtihon** [comment]
Done

**Comment by comtihon** [comment]
Please don't forget about this. :)

**Comment by bwegh** [comment]
well there are still your headers, the files look now really strange.
feel free to add a contributors file or so if you want to have your name somewhere.

**Comment by comtihon** [comment]
this is default headers of my IDE. I don't mind of removing all personal info as author, copyrite and created date, but think, that doc section is useful.

**Comment by comtihon** [comment]
Please, check - I removed them.

**Comment by bwegh** [comment]
thanks for your help

**Pull request merged**
